### ISSUE TITLE
Add module-info or Automatic-Module-Name for use with Java 9+ modules

### ISSUE THREAD

**Issue by BomBardyGamer** [hrldcpr/pcollections#108]
This library is currently very difficult to use in projects that define modules, as because no module or automatic name is supplied, the code in this project belongs to the unnamed module, which cannot be depended on. At the moment, what I have to do is use a tool that can remap the JAR to define the module-info, which isn't a great solution. It would be nice if this was supported directly in the project.

As mentioned above, this can be done via one of two methods:
* Create a `module-info.java` file and use the multi-release JAR mechanism to include the module-info for use with Java 9+ only (recommended)
* Add the `Automatic-Module-Name` attribute to the manifest, which will define the name that a synthetic module that exports everything will be.

I will happily create a pull request for this, but I am not sure which approach you would like.

**Comment by hrldcpr** [comment]
Adding `module-info.java` sounds good to me, assuming it doesn't somehow interfere with Java 8 support?

I (clearly) haven't used modules, so I'll take you up on the pull request offer, thanks!

**Comment by hrldcpr** [comment]
Alright #109 has been released as v4.0.1 - https://central.sonatype.dev/artifact/org.pcollections/pcollections/4.0.1

@BomBardyGamer When you get a chance, if you can test that it works as expected, then we can close this issue 🚀

**Comment by BomBardyGamer** [comment]
Just updated in the project I was using and it seems to compile just fine without issues, so I assume it's working fine. Going to therefore close this issue. Thanks!
