### ISSUE TITLE
[Patch] POrderedMap, and array-based implementations of that, POrderedSet, and PVector

### ISSUE THREAD

**Issue by blackdrag** [hrldcpr/pcollections#19]
_From [tsd...@gmail.com](https://code.google.com/u/106752564906713546161/) on 2011-08-18T10:01:21Z_

Hi Harold,

this patch adds the following new stuff:
- POrderedMap: interface for PMaps that preserve the insertion order
- ArrayPMap: an implementation of POrderedMap based on arrays
- ArrayPVector: an implementation of PVector based on arrays
- ArrayPSet: an implementation of POrderedSet based on arrays
- ArrayPVectorTest: a junit test for ArrayPVector

All these array-based variants are especially well-suited (efficient, both performance and memory wise) for small collections.

We use them (since yesterday!) for collection-valued attributes on nodes and edges of graphs in our graph library JGraLab.  There you have thousands or even millions of nodes and edges, but their collection-valued attributes are all rather small, so small memory footprints are very important for us.

I think there are many similar use-cases that can benefit from these variants, too, so it'd be great if you included them in the pcollections proper.

_Original issue: http://code.google.com/p/pcollections/issues/detail?id=19_

**Comment by ilya-g** [comment]
Does anyone know where to find that patch?

**Comment by hrldcpr** [comment]
RIP
