### ISSUE TITLE
SortedSet/TreeSet alternative?

### ISSUE THREAD

**Issue by blackdrag** [hrldcpr/pcollections#20]
_From [janvanbesien@gmail.com](https://code.google.com/u/janvanbesien@gmail.com/) on 2011-10-11T15:52:20Z_

I was wondering if any of the collections offered by pcollections offer an alternative to java.util.SortedSet and java.util.TreeSet.

I would thus like to have a persistent SortedSet implementation with at least the following methods (with semantics as defined by java.util.SortedSet):
- first
- last
- headSet
- tailSet

_Original issue: http://code.google.com/p/pcollections/issues/detail?id=20_

**Comment by hrldcpr** [comment]
Fixed by #92
