### ISSUE TITLE
Not clear if sets are thread-safe

### ISSUE THREAD

**Issue by blackdrag** [hrldcpr/pcollections#22]
_From [li...@selckin.be](https://code.google.com/u/110766422158211199599/) on 2012-08-01T17:12:27Z_

The front page says: "This includes efficient, thread-safe, generic, immutable, and persistent stacks, maps, vectors, sets, and bags"

I think wow cool, i'm interested in sets, so i hit HashTreePSet on the front page http://pcollections.googlecode.com/svn/trunk/docs/org/pcollections/HashTreePSet.html Lets check out that return type http://pcollections.googlecode.com/svn/trunk/docs/org/pcollections/MapPSet.html There i find: "If the backing map is thread-safe, then this implementation is thread-safe (assuming Java's AbstractSet is thread-safe), although its iterators may not be"

So uhm cross fingers and hope for the best? maybe the iterators aren't used?

_Original issue: http://code.google.com/p/pcollections/issues/detail?id=22_

**Comment by TaiJuWu** [comment]
Hi @hrldcpr ,
I want to know the `HashPMap` is still thread-safe?
Could you help to explain?

**Comment by hrldcpr** [comment]
Hi @TaiJuWu sorry for the slow response. `HashPMap.update()` is definitely thread-safe. We should really make the documentation clearer, sorry about that.
