### ISSUE TITLE
PStack.reverse

### ISSUE THREAD

**Issue by blackdrag** [hrldcpr/pcollections#23]
_From [gromop...@gmail.com](https://code.google.com/u/103704723598070992557/) on 2013-03-16T10:31:51Z_

Cons-based lists in many languages are accompanied with reverse functionality which creates a cons-based list with the same elements in the reversed order. Using pcollections, I find I need this too. There's no easy alternaltive, as Collections.reverse() returns a normal List, not a PStack. So I'd appreciate if a method could be added:
 PStack.reverse() returning another PStack.

The implementation should be very easy and straightforward, but I can provide a patch if you like.

_Original issue: http://code.google.com/p/pcollections/issues/detail?id=23_

**Comment by hrldcpr** [comment]
A stack can be reversed easily already, because `ConsPStack.plusAll()` reverses (which is confusing but makes sense if you think about it) …so I'll close this but here's the code if anyone is looking:

```java
ConsPStack stack = …;
ConsPStack reversed = ConsPStack.empty().plusAll(stack);
```

**Comment by hrldcpr** [comment]
See also #77
