### ISSUE TITLE
Enforce formatting to reduce whitespace noise in patches.

### ISSUE THREAD

**Issue by nedtwigg** [hrldcpr/pcollections#32]
Hi there!  There's a Gradle plugin called Spotless that can enforce and apply formatting.  It enforces license header, whitespace in the code, and import ordering (a-la carte, if you don't want all three).

``` groovy
apply 'spotless'
spotless {
    java {
        licenseHeaderFile   'spotless.license.java'         // License header file
        importOrderFile     'spotless.importorder'          // An import ordering file, exported from Eclipse
        eclipseFormatFile   'spotless.eclipseformat.xml'    // XML file dumped out by the Eclipse formatter
    }
    format 'misc', {
        target '**/.gitignore', '**/*.gradle', '**/*.md', '**/*.sh'
        indentWithTabs()
        trimTrailingWhitespace()
        endWithNewline()
    }
}
```

It adds a task to `gradlew build` that will throw a descriptive error if any files don't match the required formatting.  `gradlew spotlessApply` automatically applies all of the formatting rules to the code (and build files, doc files, etc).  It uses the Eclipse formatter, but it doesn't require anyone to use Eclipse, it's all invisible to the user once it's setup.

The first time you run `gradlew spotlessApply`, you get a terrible commit where everything in the world changed, like [this](https://github.com/diffplug/matfilerw/commit/179d0ca9608cd2702c8f140ddf16a7a703187a0f), but from then on, every commit that passes CI is guaranteed to be formatted (and thus diff nicely).

Here's some projects that [use it](https://github.com/diffplug/spotless#example-configurations-from-real-world-projects).

Would you like a PR that adds this?

**Comment by hrldcpr** [comment]
Fixed by 57e2e04
