### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [hrldcpr/pcollections#42]
Hi
The following source files are without license headers.

./src/test/java/org/pcollections/tests/TreePVectorTest.java
./src/test/java/org/pcollections/tests/UtilityTest.java
./src/test/java/org/pcollections/tests/IntTreePMapTest.java
./src/test/java/org/pcollections/tests/HashPMapTest.java
./src/test/java/org/pcollections/tests/Benchmarks.java
./src/test/java/org/pcollections/tests/OrderedPSetTest.java
./src/test/java/org/pcollections/tests/ConsPStackTest.java
./src/main/java/org/pcollections/OrderedPSet.java
./src/main/java/org/pcollections/PVector.java
./src/main/java/org/pcollections/HashTreePSet.java
./src/main/java/org/pcollections/SimpleImmutableEntry.java
./src/main/java/org/pcollections/POrderedSet.java
./src/main/java/org/pcollections/PStack.java
./src/main/java/org/pcollections/MapPSet.java
./src/main/java/org/pcollections/MapPBag.java
./src/main/java/org/pcollections/PBag.java
./src/main/java/org/pcollections/ConsPStack.java
./src/main/java/org/pcollections/PCollection.java
./src/main/java/org/pcollections/PMap.java
./src/main/java/org/pcollections/PSet.java
./src/main/java/org/pcollections/HashTreePBag.java
./src/main/java/org/pcollections/AmortizedPQueue.java
./src/main/java/org/pcollections/HashTreePMap.java
./src/main/java/org/pcollections/IntTree.java
./src/main/java/org/pcollections/HashPMap.java
./src/main/java/org/pcollections/TreePVector.java
./src/main/java/org/pcollections/IntTreePMap.java
./src/main/java/org/pcollections/Empty.java
./src/main/java/org/pcollections/PQueue.java
./src/main/java/org/pcollections/PSequence.java

Please, confirm the licensing of code and/or content/s, and add license headers

https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance

Regards

**Comment by nedtwigg** [comment]
Might wanna use [Spotless](https://github.com/diffplug/spotless) to keep this enforced.

```
plugins {
    id "com.diffplug.gradle.spotless" version "2.0.0"
}

spotless {
    java {
        licenseHeaderFile 'license.txt'
    }
}
```

Can also enforce formatting rules using eclipse formatter, but only if you want that level of strictness.

**Comment by puntogil** [comment]
hi
any news?
regards
