### ISSUE TITLE
README: jmh start?

### ISSUE THREAD

**Issue by about-midnight** [hrldcpr/pcollections#44]
@blackdrag Hi, there. Tried running ./gradlew jmh and it failed. Never used jmh before - could you help get it running? 

some logs:

./gradlew build
./gradlew jmh 

```
:compileJmhJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
/home/m/Workspace/Java/Samples/pcollections/src/jmh/java/org/pcollections/benchmark/Benchmarks.java:18: error: package org.pcollections.tests.Benchmarks does not exist
import static org.pcollections.tests.Benchmarks.CollectionType.*;
```

It warns about 1.6 path. Must I install jdk 1.6 as an alternative?

java -version

```
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

echo $JAVA_HOME 

`/opt/oracle/jdk1.8.0_101`

**Comment by tatacalu** [comment]
This pull request should fix the issue for you, if it gets merged: https://github.com/hrldcpr/pcollections/pull/49
