### ISSUE TITLE
[Question] Tree vs Trie

### ISSUE THREAD

**Issue by ArazAbishov** [hrldcpr/pcollections#53]
Is there any particular reason not to use Trie as a main building block for List?

**Comment by blackdrag** [comment]
For a Trie you need a key. You can maybe use the hashcode as Trie key, but then you of course also require that method been implemented in a useful way and with good performance. Last but not least usually do not really go for allowing multiples. A list does not really require equals, hascode, compareable, some kind of key or single values in general. Of course specific lists can be different here

**Comment by ArazAbishov** [comment]
@blackdrag Isn't hashcode required to be implemented correctly no matter what? For instance if you want to use an object as a key in the map, it is your responsibility to make sure that `hashCode()` is implemented correctly.

**Comment by blackdrag** [comment]
as key in a map yes. For an oridinary simple list equals is enough. But for some cases you need not only an implementation of hashcode, but also a fast one.

**Comment by hrldcpr** [comment]
There are two `java.util.List` implementations in PCollections—ConsPStack and TreePVector.

The former is just a linked list but [the latter uses a balanced tree](https://github.com/hrldcpr/pcollections/blob/master/src/main/java/org/pcollections/IntTreePMap.java). I'm not sure if that answers your question, but I'll close this issue for now.

(Also sorry for the slow reply, apparently I've never had notifications enabled for this repository, I'm glad Jochen is on top of it!)
