### ISSUE TITLE
Minimum Java version Update

### ISSUE THREAD

**Issue by matei-dragu** [hrldcpr/pcollections#60]
Currently PCollections targets Java 6 - a very old and no longer supported version.

Currently Java 8 is the oldest version still publicly supported, with the last version of Java 7 for example (7u80) having been released about 3 years ago: https://en.wikipedia.org/wiki/Java_version_history#Java_7_updates

How about making Java 8 the minimum supported version?

**Comment by hrldcpr** [comment]
Sounds good to me. Guava also targets Java 8 now, so it seems like that's acceptable for utility libraries at this point.

**Comment by matei-dragu** [comment]
Great, will create a PR for this.

**Comment by hrldcpr** [comment]
@matei-dragu whoops sorry I went ahead and made the change.

Also a nice side-effect is we can remove the SimpleImmutableEntry class, since it's built in to Java 1.6+ 🎉

**Comment by matei-dragu** [comment]
Great! JUnit 5 can be used in this case (see PR) for testing.
