### ISSUE TITLE
org.pcollections.PMap should not extend java.util.Map

### ISSUE THREAD

**Issue by imrafaelmerino** [hrldcpr/pcollections#78]
From my point of view, it's confusing to be able to call java.util.Map methods from
PMap. They shouldn't be exposed to the final user.

Every public method on PMap has to return another PMap

What do you think?

**Comment by hrldcpr** [comment]
Hi Rafael!

I agree this can be confusing, but I think the benefit of being able to interoperate with code and libraries that weren't written for PCollections makes it worth the tradeoff. I.e. being able to pass a `PMap` into any code that expects a `Map`, as long as it doesn't try to mutate it.

(And all of Java Collections interfaces do specify that mutation operations are optional, so `PMap` really is a valid `Map` subtype.)

I hope that seems reasonable to you, thanks for the input
