### ISSUE TITLE
Remove personal details from older commits

### ISSUE THREAD

**Issue by matei-dragu** [hrldcpr/pcollections#91]
I have realised that my personal details have leaked in some of the commits that have been merged in master a few years ago - can those commits be amended to remove them by any chance?

**Comment by hrldcpr** [comment]
Of course! I'll look into it this weekend

**Comment by matei-dragu** [comment]
Thank you very much in advance, please let me know if you need extra details about this.

**Comment by hrldcpr** [comment]
Weekend has gotten busier than expected, but will do this on Monday fyi.

**Comment by matei-dragu** [comment]
No problem @hrldcpr - thanks a lot!

**Comment by hrldcpr** [comment]
I guess I do need extra details about what you'd like amended / I didn't see anything obvious in the commit logs. You can email me at the address in my profile if you'd like to avoid pointing out the specific issue here.

**Comment by matei-dragu** [comment]
@hrldcpr - I have just sent an e-mail to the address in your profile

**Comment by matei-dragu** [comment]
Fixed, thanks a lot @hrldcpr !!!
